### ISSUE TITLE
api-server.js is not working when deployed to the vercel 

### ISSUE THREAD

**Issue by skirdey** [auth0-samples/auth0-nextjs-samples#130]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-nextjs-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Deploying the sample app on vercel doesn't seem to run the api-server.js - is it expected?
It works locally, but not when accessed from the vercel deployed app. 

The function calls to localhost:3001 or 127.0.0.1:3001 return connection refused when called from /api/whatever. 

### Reproduction

deploy to vercel, try to access shows

**Comment by adamjmcgrath** [comment]
Hi @skirdey - thanks for raising this.

The api-server is an express server, designed to demonstrate an external api on your local machine. If you want to deploy it to Vercel, have a look at https://vercel.com/guides/using-express-with-vercel#standalone-express - this is outside the scope of this example.
