### ISSUE TITLE
Next JS App Router - Refresh Tokens

### ISSUE THREAD

**Issue by hobadams** [auth0-samples/auth0-nextjs-samples#145]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-nextjs-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I wanted to know if refresh tokens work with the Next js running on app router (not pages).

### Describe the ideal solution

The ideal solution would be for refresh tokens to work out of the box or a simple integration guide to be added

### Alternatives and current workarounds

At the moment i have the session lifetime to 24 hours. It's annoying and doesn't feel like the best for security

### Additional context

Our app is running Next js 14 with app router.

It's a auth protected app

We'd like users to only have to log in once a month but have short lived auth tokens and refresh tokens in place.

I've tried using Next Auth but this causes refresh tokens to be generated every refresh because the middleware can't write cookies. I'd like to try this package as an alternative.

**Comment by Widcket** [comment]
👋🏼 @hobadams, thanks for raising this.

The SDK supports refresh tokens, but it doesn't request them by default. Please check out https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#getting-a-refresh-token.

**Comment by hobadams** [comment]
wow, thanks @Widcket, I assumed it would be much more involved than that. And that works with the App router and middleware?

**Comment by Widcket** [comment]
Yes, that works with the app router and middleware. Please see https://github.com/auth0/nextjs-auth0?tab=readme-ov-file#using-this-sdk-with-react-server-components for more information about limitations with React Server Components.
