### ISSUE TITLE
signup with auth0

### ISSUE THREAD

**Issue by Malith077** [auth0-samples/auth0-nextjs-samples#23]
I have implemented siging up a user using the auth0 api and is it possible that I could still use the hooks available in auth0/nextjs-auth0 to store the user across the application, and login to the application using the universal login, and store the logged in user across the application as well?

**Comment by adamjmcgrath** [comment]
Hi @Malith077 - `nextjs-auth0` only supports using the Universal Login Page for authentication. If you want to use your own bespoke embedded system for doing auth then this SDK won't be suitable for them as we don’t expose the low level functionality for managing the session.

Auth0 recommends using the Universal Login Page over embedded but if you want to persevere with embedded, [Vercel recommends `iron-session`](https://nextjs.org/docs/authentication#bring-your-own-database) for a low-level, encrypted, and stateless session utility.

**Comment by Malith077** [comment]
Hi @adamjmcgrath So after I signup a user then I have to redirect them to complete the login. After that I'll be able to keep the user across the application?

Is there any  other auth0 npm package that I could use which doesn't redirect the user to ULP after signing up? In my use case, I need to signup a user then redirect them to a "Thank you for signing up" page. However, this particular page has to have the signed up user in the navbar right away. 
Appriciate some directions. Thanks.

**Comment by adamjmcgrath** [comment]
> So after I signup a user then I have to redirect them to complete the login. After that I'll be able to keep the user across the application?

Correct

> Is there any other auth0 npm package that I could use which doesn't redirect the user to ULP after signing up?

Only our legacy SDKs do embedded auth (like auth0.js see https://github.com/auth0/auth0.js#auth0authentication)

**Comment by adamjmcgrath** [comment]
Closing - feel free to ping me if you want me to reopen
