### ISSUE TITLE
'checks.state argument is missing' error in cypress tests

### ISSUE THREAD

**Issue by abdrah1** [auth0-samples/auth0-nextjs-samples#26]
![Screenshot 2022-03-14 at 15 00 25](https://user-images.githubusercontent.com/86606646/158203522-25208280-1c60-4de0-8b67-aecfc4bfc83b.png)

Steps to reproduce: 
1. complete the .env.local file in the Sample-01/.env.local file i.e. fill in the details from the auth0 regular web application 
2. ensure callback/logout urls are added correctly in auth0 
3. build using npm run build
4. test that app is working by running `npm run dev` - test login, logout and ssr route - test on http://0.0.0.0:3000/
5. add the username/password as env vars in cypress
6. change the baseUrl in cypress to match the basepath in auth0 callback urls as well as what's configured in the .local.env file for the actual application
7. run `npm run test:integration:watch` to run cypress and select the login test from the watcher
8. notice the error

**Comment by AlexcastroDev** [comment]
Same error here, if i found a solution, ill reply this issue

**Comment by jalexandremoreira** [comment]
Same error here. Wondering if anyone has found a solution for this.

**Comment by jalexandremoreira** [comment]
I found a solution for this. I just redirect back to the homepage after the login process is done, instead of waiting for the redirect from auth0

`cy.visit("http://localhost:3000/");`
