### ISSUE TITLE
Some links to usecases in README for Sample01 are not aligned with current position of relevant code blocks

### ISSUE THREAD

**Issue by ccp92** [auth0-samples/auth0-nextjs-samples#68]
On https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01 the following links have hardcoded line references that are out of date:

- [Login](https://github.com/auth0-samples/auth0-nextjs-samples/blob/415af75b3e2c64e39f29b861d609994247e50fa0/Sample-01/README.md?plain=1#L7)
- [Logout](https://github.com/auth0-samples/auth0-nextjs-samples/blob/415af75b3e2c64e39f29b861d609994247e50fa0/Sample-01/README.md?plain=1#L8)
- [Protecting client-side rendered pages](https://github.com/auth0-samples/auth0-nextjs-samples/blob/415af75b3e2c64e39f29b861d609994247e50fa0/Sample-01/README.md?plain=1#L10)

**Comment by Widcket** [comment]
Thanks @ccp92 for raising this, it's fixed now.
