### ISSUE TITLE
User profile state not saved. Switching to loading / undefined state on route change.

### ISSUE THREAD

**Issue by jackblackCH** [auth0-samples/auth0-nextjs-samples#81]
The example works but on every route change, the user profile component's `user` from `useUser` is shortly undefined and the component shoes "...Loading" even though the session and cookie still exists.

I am using NextJS 13 with new app directory.

Is there a way keep the logged in state?

**Comment by Widcket** [comment]
Hi @jackblackCH, thanks for raising this and apologies for the delay. The app directory introduced with Next.js 13 is currently in beta, and Vercel [does not recommend](https://nextjs.org/blog/next-13#new-app-directory-beta) using it in production. As such, this SDK does not support it yet.

**Comment by sockdrawermoney** [comment]
@Widcket just as an fyi, the url linked to here now says

> Next.js 13 and the pages directory are stable and ready for production.
